[package]
name = "typst-fmt"
version = "0.1.0"
edition = "2021"
authors = ["Astrale <ash4567@outlook.fr>"]
rust-version = "1.56"
description = "A soon to be formatter for the typst lang"
readme = "README.md"
repository = "https://github.com/astrale-sharp/typst-fmt"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "development-tools"]


#[[bin]]
#name = "typst-fmt"
#path = "src/main.rs"

[dependencies]
clap = { version = "4.2.0", features = ["derive"] }
globmatch = "0.2.3"
itertools = "0.10.5"
log = "0.4.17"
regex = "1.7.3"
toml = "0.7.3"
typst = { git = "https://github.com/typst/typst.git" }
env_logger = "0.10.0"


[dev-dependencies]
similar-asserts = "1.4.2"
